New Python Example
pomerium/enterprise-client-python pull request #3
Opened 2021-09-16 20:35 UTC by alexfornuto

This PR moves the existing example script into a sub-directory, and creates another example.

This new example script reads a yaml-formatted list of hosts and generated TCP routes for them. 

## Remaining Work

- [ ] Replace psudo code with actual code
- [ ] Replace my existing code with good code
- [ ] Testing

2021-09-20 18:13 UTC, travisgroth requested changes

2021-09-21 14:29 UTC, alexfornuto commented on examples/generateSshRoutes.py
> +# Function listPols returns the ID from the policies provided as a single array.
```suggestion
# Function getPolIDs returns the ID from the policies provided as a single array.
```

2021-09-21 14:29 UTC, alexfornuto commented on examples/generateSshRoutes.py
> +    print(p)
Whoops, debugging artifact.

2021-09-21 21:32 UTC, travisgroth approved these changes

2021-09-21 21:35 UTC, merged